version: '2.1'

services:

  aad-ui:
    container_name: aad-ui
    hostname: aad-ui
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${UI_PORT:-3002}:4100
    environment:
      - NODE_ENV=development
    networks:
      - default
