version: '3.5'

services:

  aad-ui:
    container_name: aad-ui
    hostname: aad-ui
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - ${UI_PORT:-3001}:4100
    environment:
      - NODE_ENV=development
    networks:
      - default
