export const APP_LOAD = 'APP_LOAD';
export const REDIRECT = 'REDIRECT';
export const LOGOUT = 'LOGOUT';
export const ASYNC_START = 'ASYNC_START';
export const ASYNC_END = 'ASYNC_END';

export const LANDING_PAGE_LOADED = 'LANDING_PAGE_LOADED';
export const LANDING_PAGE_UNLOADED = 'LANDING_PAGE_UNLOADED';

export const UPDATE_FIELD_AUTH = 'UPDATE_FIELD_AUTH';
export const LOGIN = 'LOGIN';
export const LOGIN_PAGE_UNLOADED = 'LOGIN_PAGE_UNLOADED';
export const REGISTER = 'REGISTER';
export const REGISTER_PAGE_UNLOADED = 'REGISTER_PAGE_UNLOADED';

export const PORTAL_PAGE_LOADED = 'PORTAL_PAGE_LOADED';
export const PORTAL_PAGE_UNLOADED = 'PORTAL_PAGE_UNLOADED';

export const UPDATE_USER_INFO = 'UPDATE_USER_INFO';
export const USER_INFO_UNLOADED = 'USER_INFO_UNLOADED';
export const USER_INFO_LOADED = 'USER_INFO_LOADED';

export const OPEN_REVIEW_FORM = 'OPEN_REVIEW_FORM';
export const REVIEW_FORM_LOADED = 'REVIEW_FORM_LOADED';
export const REVIEW_FORM_UNLOADED = 'REVIEW_FORM_UNLOADED';

export const MY_REVIEWS_LOADED = 'MY_REVIEWS_LOADED';
export const MY_REVIEWS_UNLOADED = 'MY_REVIEWS_UNLOADED';
